version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/MixinNetwork/bot-api-go-client
    versions:
    - 1.2.1
    - 1.3.0
